steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/devops-dev', '.']

# Push the Docker image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/devops-dev']

# Deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    - 'run'
    - '--filename=gke.yaml'
    - '--image=gcr.io/$PROJECT_ID/devops-dev'
    - '--location=us-central1-c'
    - '--cluster=cluster-1'
    - '--namespace=devops-development'