steps:
#build
- name: 'gcr.io/cloud-build/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/devops-1','.']
#push
- name: 'gcr.io/cloud-build/docker'
  args: ['push','gcr.io/$PROJECT_ID/devops-1']
#deploy
- name: 'gcr.io/cloud-build/gke-deploy'
  args:
  - run
  - --filename = gke.yaml
  - --image = gcr.io/$PROJECT_ID/devops-1
  - --location = us-central1-c
  - --cludter = cluster-1
  - --namespace = devops