apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-qke
        image: gcr.io/devops-1-402605/devops-1:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"